### PR TITLE
Updated minimum boost version required to 1.66.0.

### PR DESCRIPTION
**Pull request by redboltz**

### CODE REVIEW

**Comment by jseela** [comment]
Oh, so this is where my compiler issues are coming from.
The CMakeLists.txt should probably reflect this, too.

#403

**Comment by redboltz** [comment]
Do you mean
https://github.com/redboltz/mqtt_cpp/blob/master/CMakeLists.txt#L99-L110 ?

If it dos, I should update from 1.59.0 to 1.66.0.
In addition, I noticed that sing 1.66.0, beast is a part of boost. So I don't need to contain beast as the sub-module.

**Comment by jseela** [comment]
That is exactly what I meant.
And you are right, the additional checks for beast should not be necessary. I updated my pull request for that.

**Comment by redboltz** [comment]
Thanks. I will update the PR soon.

**Comment by jseela** [comment]
thank you, too

**Pull request merged**
