### PR TITLE
The beginning of support for session expiry interval, message expiry …

### PR DESCRIPTION
**Pull request by jonesmz**
…interval, and will delay interval in the test broker

Not ready to submit yet.

@redboltz Can you please review and provide feedback on the implementation so far?

### CODE REVIEW

**Comment by jonesmz** [comment]
Related to https://github.com/redboltz/mqtt_cpp/issues/340

**Comment by kleunen** [comment]
What is the status of this PR? I looked at the broker code and it seems there is session expiry?

**Comment by jonesmz** [comment]
@kleunen abandoned, basically. I no longer work at the company that was using mqtt_cpp , so my contributions will be low in the future.

Session expirary was added after I initially created this PR.

I attempted to re-work this PR after session expiry was merged in order to incorporate those changes, the message expiry functionality was never 100% finished.

Please feel free to take over this PR, or implement the functionality in a way that directly conflicts with this PR.

**Comment by kleunen** [comment]
@jonesmz so i understand correctly, session expiry is working, but message expiry is not?

**Comment by jonesmz** [comment]
Yes I believe that is the case.

**Comment by kleunen** [comment]
This PR is included in merge of PR #731

**Comment by jonesmz** [comment]
Superseded by other contributors work, closing.

**Pull request closed without merging**
