### PR TITLE
Add wildcard handling to topics in the test broker

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by redboltz** [comment]
Is this refined version of #558 ?
Can I close #558 after #671 merged ?

**Comment by jonesmz** [comment]
@redboltz No, https://github.com/redboltz/mqtt_cpp/pull/558 is a better approach, but not finished.

**Comment by redboltz** [comment]
Should I merge #671 ? Doesn't #671 disturb #558 ?

**Comment by jonesmz** [comment]
This PR will make #558 have merge conflicts, but I don't believe that this PR will make implementing #558 any more complicated.

#558 uses the "Trie" datastructure to handle mqtt subscriptions, which is substantially better than boost-multi-index. This PR will not change how #558 is implemented, so any merge conflicts are not a big problem.

**Comment by jonesmz** [comment]
The reason for this PR is to allow wildcard handling right now, until #558 is finished.

**Comment by redboltz** [comment]
I understand. Thank you for elaborating.

**Pull request merged**
