### PR TITLE
Add constexpr keyword to lots of small functions where possible

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by jonesmz** [comment]
It's very unclear to me why the code coverage would have changed due to this PR.

**Comment by redboltz** [comment]
I re-run the bottom 4 tasks on travis-ci. They send codecov reports. 
Sometimes some of them seems to fail to send report and it is NOT logged.

Perhaps codecov has time limit from the first report receiving to the last report receiving.

To be honest, I don't read much the codecov document. I just modify some example.

Here is codecov report code:
https://github.com/redboltz/mqtt_cpp/blob/master/.travis.yml#L102-L107

I guess that we can improve it.

**Comment by redboltz** [comment]
Recovered by re-run bottom four builds. `- Coverage   84.94%   84.93%   -0.01%     `

**Comment by jonesmz** [comment]
Still weird that the coverage decreased even though I removed an unused function. Oh well.

**Comment by jonesmz** [comment]
Either way, I think this code is ready to merge.

Let me know if there's anything you want me to change.

**Comment by redboltz** [comment]
Looks good to me. Thanks.

**Pull request merged**
