### PR TITLE
Set CXX to environment variable.

### PR DESCRIPTION
**Pull request by redboltz**

### CODE REVIEW

**Comment by redboltz** [comment]
It seems that compiler selection does not works well on the current master.

**Comment by redboltz** [comment]
I noticed that `__GLIBCXX__` cannot be compared using '<' like operators.

|gcc version|__GLIBCXX__`|workaround|
|---|---|---|
|<=7.3.0|<=20180125|required|
|7.4.0|20181206|required|
|7.5.0|20191114|required|
|8.1.0|20180502|required|
|8.2.0|20180726|not required|
|8.3.0|20190222|not required|
|9.1.0|20190503|required|

**Comment by jonesmz** [comment]
Why not set compiler using

cmake -DCMAKE_CXX_COMPILER=Clang++ ?

**Comment by redboltz** [comment]
> Why not set compiler using
> 
> cmake -DCMAKE_CXX_COMPILER=Clang++ ?

It is historical reason. Now, CI uses only cmake. So we can replace.
But if some package requires build from the source and the source uses autotools instead of cmake, the environment variable CXX is useful.
It was happened on travis-ci, and move to github actions directly. That is the current status.

**Comment by redboltz** [comment]
Never mind the comment above. I got confused with msgpack-c.

**Pull request merged**
