### PR TITLE
Use std::move instead of std::forward in null_strand

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by jonesmz** [comment]
@redboltz 

Error on Github Actions is:

> as_buffer_async_pubsub_2.cpp:(.text.startup+0x1bf): undefined reference to `boost::unit_test::decorator::collector_t::instance()'

Does not seem related to my PR.

Have you seen before?

**Comment by redboltz** [comment]
I've never seen it. Currently, gha.yml sets `ubuntu-latest`.
I guess that os image or apt repository might be updated.

I've noticed that 
https://github.com/jonesmz/mqtt_cpp/blob/patch-1/.github/workflows/gha.yml#L91
uses boost1.67 but got boost1.69.
See https://github.com/redboltz/mqtt_cpp/runs/401598995#step:4:86

The last successful build detect boost1.67.
https://github.com/redboltz/mqtt_cpp/runs/394733364#step:4:74

I guess that this is something related.

Could you investigate it?

**Comment by redboltz** [comment]
Finally, I found the reason of the problem. `ubuntu-latest` has Boost.1.69 but is seems to be incomplete. I'm not sure it is used to exist or not. But it wasn't harmful but recently it became harmful. I explicitly pass `-DBOOST_ROOT` to cmake. Now cmake uses Boost.1.67 correctly.

Could you rebase your PR from master?

**Comment by jonesmz** [comment]
What caused the build to be canceled?

**Comment by redboltz** [comment]
I re-ran again and again yesterday. I don't know why but it seems that macos(3) is always cancelled. I just re-started CI process now.

**Pull request merged**
