### PR TITLE
Add checked move

### PR DESCRIPTION
**Pull request by redboltz**

### CODE REVIEW

**Comment by redboltz** [comment]
I'm not sure the name of the function `force_move()` is appropriate?
Other choice is `checked_move()`. Or something else...

**Comment by jonesmz** [comment]
I'm not sure I understand the goal of this change.

Just to ensure that std::move() is only called on things that will *actually* be moved?

Is there a bug?

Or is this to just make the code easier to understand?

**Comment by redboltz** [comment]
See https://stackoverflow.com/questions/57105812/how-to-detect-unexpected-copy-in-move-expected-case/57106531#57106531

`std::move(v)` invokes copy constructor if v is not movable but copyable. 
But in mqtt_cpp, I don't expect such behavior. When I call `std::move()`, I always expect move operation. So I need to avoid fallback copy operation. The PR does it.

The PR contains two commits. The first one is inoculated wrapped move. Then I got some unexpected copy fallbacks. The second commit fixed them.

**Comment by jonesmz** [comment]
Alright, that's reasonable

**Comment by redboltz** [comment]
https://github.com/redboltz/mqtt_cpp/pull/378/files#diff-45ca9626e6c7c611be2ceb2ff63031a5R470

I replaced move with copy at the point above.

See
https://stackoverflow.com/questions/57335172/is-there-any-way-to-move-an-element-from-ordered-index-ed-multi-index

In `modify()` function, if the element in the container is moved, then access moved from object to re-arrange elements.

**Pull request merged**
