### PR TITLE
Kleunen master mg2

### PR DESCRIPTION
**Pull request by redboltz**

### CODE REVIEW

**Comment by kleunen** [comment]
Yes, this looks ok. Only coding style changes, all test pass. Indeed it has become a massive PR.

**Comment by redboltz** [comment]
I force updated the PR.
See https://github.com/redboltz/mqtt_cpp/pull/921/commits/85cfa6f694b1905efd92bd7c7c1792ed755aed39

**Comment by kleunen** [comment]
> 

Looks good

**Comment by redboltz** [comment]
Merged. Thank you for the great work !!

Could you update https://github.com/redboltz/mqtt_cpp/wiki/Authentication-and-Authorization ?
I think that you have write permission.

**Comment by kleunen** [comment]
Excellent.

I will update the documentation

**Pull request merged**
