### PR TITLE
Incorrect include of boost unit test in global_fixture.hpp

### PR DESCRIPTION
**Pull request by kleunen**
The header file 'global_fixture.hpp' was including the wrong boost unit test header file, causing a compilation error on windows. 
http://boost.2283326.n4.nabble.com/Boost-unit-test-cpp-problem-when-try-to-compile-simple-program-td2596687.html

> You need different include than. Can't have it both ways. Either you include
> library implementation or you link with it.
>
> Use boost/test/unit_test.hpp

### CODE REVIEW

**Comment by redboltz** [comment]
Some of azure build pipelines are failed.
I re-run failed build but got the same result.

It seems that the error is caused by https://github.com/actions/virtual-environments/issues/1847
I guess that some of your builds just across vm image update.
It seems that you need to update the boost version.

**Comment by kleunen** [comment]
> It seems that you need to update the boost version.

you mean my local version ?

**Comment by kleunen** [comment]
> It seems that you need to update the boost version.

It took me a moment, to understand what you were saying

**Comment by redboltz** [comment]
Thank you for updating! 
Your fix works perfectly.

**Pull request merged**
