### PR TITLE
Subscription map updated checking of subscription path

### PR DESCRIPTION
**Pull request by kleunen**

### CODE REVIEW

**Comment by redboltz** [comment]
I noticed that mqtt_valid_topic and mqtt_valid_subscription have prefix mqtt_. It isn't required.
Could you remove this? 

It seems that those functions are not called. Of course the branch new_wc doesn't contain test_broker.hpp updates. So I've also checked #558. Who calls them?

Is function name and parameter name `topic` and `subscription` appropriate?
I use the name `topic_filter` for wildcard permitted place. For example, topic filter could be `topic1`, `a/+/b`, and `a/#`. In this case, `topic_filter` is appropriate name.
Note: The current master branch might violate this rule somewhere, but it should be fixed.

I'm not sure the difference between mqtt_valid_topic and mqtt_valid_subscription. The master branch only has mqtt_valid_topic_filter and it is called from compare_topic_filter(). compare_topic_filter() is called from linear search algorithm. I guess that your approach is very different from compare_topic_filter().

**Comment by redboltz** [comment]
After you update #684, if needed, then I will merge it to new_wc. Then move on the next step. The next step means updating test_broker.hpp to replace compare_topic_filter() with trie version. I'm not sure how to gather matched subscriptions using trie.

For example, a client subscribe `a/+/c`, `a/b/c`, and `a/#`. When a publisher (client) publish to `a/b/c`, then the broker needs to deliver the publish message to `a/+/c`, `a/b/c`, and `a/#` subscriptions.

**Comment by kleunen** [comment]
> After you update #684, if needed, then I will merge it to new_wc. Then move on the next step. The next step means updating test_broker.hpp to replace compare_topic_filter() with trie version. I'm not sure how to gather matched subscriptions using trie.
> 
> For example, a client subscribe `a/+/c`, `a/b/c`, and `a/#`. When a publisher (client) publish to `a/b/c`, then the broker needs to deliver the publish message to `a/+/c`, `a/b/c`, and `a/#` subscriptions.

yes, that is possible with the trie.

**Comment by kleunen** [comment]
> compare_topic_filter



> compare_topic_filter() is called from linear search algorithm. I guess that your approach is very different from compare_topic_filter().

yes, compare_topic_filter is the linear search approach, it is not needed anymore if you use the trie approach

**Comment by kleunen** [comment]
> I'm not sure the difference between mqtt_valid_topic and mqtt_valid_subscription.

mqtt_valid_topic should be used when a message is published to a topic. The published topic should be a valid topic (not empty, does not contain \0, and does not contain wildcards). 

mqtt_valid_subscription checks whether a subscription is valid. A subscription is allowed to contain wildcards. You named this validate_topic_filter with argument topic_filter, subscription = topic filter

**Comment by redboltz** [comment]
> mqtt_valid_subscription = validate_topic_filter and
> mqtt_valid_topic = validate_topic_name
> 
> you can replace them. mqtt_valid_topic is not used by the trie, the broker should handle this.

Hmm... maybe I understand. Let me clarify.

This is the current master's validate_topic_filter() definition.
https://github.com/redboltz/mqtt_cpp/blob/9bebfc2be1c2cc864394b61c5e2e80c5e63178df/test/test_broker.hpp#L42-L114

And this the current master's validate_topic_name() definition.
https://github.com/redboltz/mqtt_cpp/blob/9bebfc2be1c2cc864394b61c5e2e80c5e63178df/test/test_broker.hpp#L144

They are the  same as mqtt_valid_subscription and mqtt_valid_topic on #684. It that right?
If it is right, then we can remove mqtt_valid_subscription and mqtt_valid_topic  from path tokenizer.hpp.

That means we don't need #684, simply just use the current master's one.

So, I will remove the functions from new_wc branch. Is that OK?

I also want to update the name of `mqtt_path_tokenizer` to `topic_filter_tokenizer`.

Then I will let you know.
When I would update #676 and merge to the master, could you implement test_broker.hpp using trie way and create the new PR for that ?

**Comment by redboltz** [comment]
> So, I will remove the functions from new_wc branch. Is that OK?
> I also want to update the name of mqtt_path_tokenizer to topic_filter_tokenizer.

I prepared #685 it is a replacement of #676 .

@kleunen ,

My plan is

1. merge #685 
1. close #676 

And then, I will ask you to update test_broker.hpp.

It this OK ?

**Comment by kleunen** [comment]
> It this OK ?

yes, that sounds OK. I am not sure what you did with the validate filter/topic function, you removed my functions and are using your and @jonesmz updated function ? 

I think there was also a comment in the validate function of @jonesmz that UTF-8 matching was required. I am not sure if anything needs to be done to get UTF-8 matching working, the topics are validated on individual byte level. Maybe some tests with UTF-8 characters need in topics and topic_filters should be added.

**Comment by redboltz** [comment]
> yes, that sounds OK. I am not sure what you did with the validate filter/topic function, you removed my functions and are using your and @jonesmz updated function ?

Ok I go forward the process.
I've already merged @jonesmz updated function  to the master. We can continue to use them.

For UTF8 checking, we can use https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/utf8encoded_strings.hpp#L47 .
But it is no cheap, so check is only work if MQTT_USE_STR_CHECK is defined.

See https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/utf8encoded_strings.hpp#L50

**Comment by kleunen** [comment]
> For UTF8 checking, we can use https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/utf8encoded_strings.hpp#L47 .
> But it is no cheap, so check is only work if MQTT_USE_STR_CHECK is defined.

I do think that is required, MQTT specification states strings are UTF-8 encoded, so validation of network input should be done, offcourse ... The performance impact is minimal i would say, not memory allocation in inner loop, just blasting away these instructions is very fast on modern CPU. No locking, no memory allocation performance, these are usually performance killers.

**Comment by redboltz** [comment]
Yes. I think that simple insert validate_contents() function.
If MQTT_USE_STR_CHECK is not defined, then it always returns valid.
User can simply define MQTT_USE_STR_CHECK to UTF8 check.

Some of user uses the broker on closed environment. It might be in the factory. So I mean ob premise case and all of clients are under control. In this case, UTF8 check is redundant. So I provide the option.

**Comment by kleunen** [comment]
> Yes. I think that simple insert validate_contents() function.
> If MQTT_USE_STR_CHECK is not defined, then it always returns valid.
> User can simply define MQTT_USE_STR_CHECK to UTF8 check.
> 
> Some of user uses the broker on closed environment. It might be in the factory. So I mean ob premise case and all of clients are under control. In this case, UTF8 check is redundant. So I provide the option.

Yes, but even if all the clients are under control, if you open a TCP/SSL port, someone else beside your clients might connect. But ok, the library focuses now on MQTT client. If you have a MQTT server, i would always recommend enabling this check, and maybe some additional input validation as well ?

**Comment by redboltz** [comment]
Length checking and invalid bit checking are already implemented and always enabled.

I agree recommending define MQTT_USE_STR_CHECK. 

NOTE: mqtt_cpp uses positive meaning flags. e.g.) MQTT_USE_TLS. And mqtt_cpp is a header only library so user need to  define them. See https://github.com/redboltz/mqtt_cpp/wiki/Config

---

This is off topic comment.

I use mqtt_cpp for my proprietary broker. It has authorization and authentication. Client is required subscribe/publish permission for each topic.
And it supports out of UTF8 string like C++ std::string. That means binary data.
For example, user can use binary data in User Property
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901054
I personally think that UTF8 limitation is too much. If I want to use binary data as User Property, I need to do something like base64 encode. MQTT is compared with HTTP. MQTT is more binary oriented. 

Anyway, it is my broker story.
mqtt_cpp should provide UTF8 validating functionality and users use it by default.

**Pull request closed without merging**
