### PR TITLE
Convert qos namespace into an enum

### PR DESCRIPTION
**Pull request by jonesmz**
Not sure we should merge this, given the large number of changes to the test code.

I think a better way to accomplish this is to have the subscribe function, instead of taking a raw uint8_t, should take a "subscribe option" type, which can be implicitly constructed from the qos enum, and has helper functions to also accept the other types of values represented by the options byte.

### CODE REVIEW

**Comment by redboltz** [comment]
> I think a better way to accomplish this is to have the subscribe function, instead of taking a raw uint8_t, should take a "subscribe option" type, which can be implicitly constructed from the qos enum, and has helper functions to also accept the other types of values represented by the options byte.

I think that the current static_cast is not good. As you mentioned, we need some mechanism to remove the static_cast. 
Could you give me some working example of "subscribe option" type on wandbox?

**Comment by jonesmz** [comment]
MQTTv3 only allows a single option to the subscribe parameter: QOS

MQTTv5 supports multiple options, all fitting within 8 bits: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901169

- Retain Handling
- RAP
- NL
- QoS
- 2 bits reserved for future use.

So we create 4 enums

```cpp
enum class retain_handling : std::uint8_t
{
    always = 0b00000000;
    if_not_exists = 0b00010000;
    never = 0b00100000;
    do_not_use = 0b00110000;
};
enum class rap : std::uint8_t
{
    Retain = 0b00001000;
    Dont = 0b00000000;
};
enum class nl : std::uint8_t
{
    yes = 0b00000100;
    no = 0b00000000;
};
enum class qos : std::uint8_t
{
    at_most_once = 0b00000000;
    at_least_once = 0b00000001;
    exactly_once = 0b00000010;
    do_not_use = 0b00000011;
};
```

And a SubscribeOptions type

```cpp
struct SubscribeOptions
{
    std::uint8_t data_;
};
```

SubscribeOptions will be implicitly constructible from each enum type, and also implicitly convertible back to std::uint8_t;

struct SubscribeOptions
{
    SubscribeOptions(retain_handling value) : data_(static_cast<std::uint8_t>(value)) { };
    SubscribeOptions(rap value) : data_(static_cast<std::uint8_t>(value)) { };
    SubscribeOptions(nl value) : data_(static_cast<std::uint8_t>(value)) { };
    SubscribeOptions(qos value) : data_(static_cast<std::uint8_t>(value)) { };

    SubscribeOptions& operator|=(retain_handling value) { data_ =| static_cast<std::uint8_t>(value); return *this; }
    SubscribeOptions& operator|=(rap value) { data_ =| static_cast<std::uint8_t>(value); return *this; }
    SubscribeOptions& operator|=(nl value) { data_ =| static_cast<std::uint8_t>(value); return *this; }
    SubscribeOptions& operator|=(qos value) { data_ =| static_cast<std::uint8_t>(value); return *this; }

    retain_handler get_retain_handler() { return static_cast<retain_handler>(data_ & 0b00110000; }
    rap get_rap() { return static_cast<rap>(data_ & 0b00001000; }
    nl get_nl() { return static_cast<nl>(data_ & 0b00000100; }
    qos get_qos() { return static_cast<qos>(data_ & 0b00000011; }

    operator std::uint8_t() { return data_; }
    std::uint8_t data_;
};
```

And the enum types also have operator| provided with each other, to ensure clean construction of SubscribeOptions.

```cpp
SubscribeOptions operator|(SubscribeOptions lhs, retain_handling rhs) { lhs |= rhs; return lhs; }
SubscribeOptions operator|(SubscribeOptions lhs, rap rhs) { lhs |= rhs; return lhs; }
SubscribeOptions operator|(SubscribeOptions lhs, nl rhs) { lhs |= rhs; return lhs; }
SubscribeOptions operator|(SubscribeOptions lhs, qos rhs) { lhs |= rhs; return lhs; }

SubscribeOptions operator|(retain_handling lhs, rap rhs) { return SubscribeOptions(lhs) | rhs; }
SubscribeOptions operator|(retain_handling lhs, nl rhs) { return SubscribeOptions(lhs) | rhs; }
SubscribeOptions operator|(retain_handling lhs, qos rhs) { return SubscribeOptions(lhs) | rhs; }

SubscribeOptions operator|(rap lhs, retain_handling rhs) { return SubscribeOptions(lhs) | rhs; }
SubscribeOptions operator|(rap lhs, nl rhs) { return SubscribeOptions(lhs) | rhs; }
SubscribeOptions operator|(rap lhs, qos rhs) { return SubscribeOptions(lhs) | rhs; }

SubscribeOptions operator|(nl lhs, retain_handling rhs) { return SubscribeOptions(lhs) | rhs; }
SubscribeOptions operator|(nl lhs, rap rhs) { return SubscribeOptions(lhs) | rhs; }
SubscribeOptions operator|(nl lhs, qos rhs) { return SubscribeOptions(lhs) | rhs; }

SubscribeOptions operator|(qos lhs, retain_handling rhs) { return SubscribeOptions(lhs) | rhs; }
SubscribeOptions operator|(qos lhs, rap rhs) { return SubscribeOptions(lhs) | rhs; }
SubscribeOptions operator|(qos lhs, nl rhs) { return SubscribeOptions(lhs) | rhs; }
```

Then use the existing API like this:

```cpp
mqtt_cpp::endpoint * endpoint;
endpoint->subscribe("topicname", qos::at_most_once); ///< Implicitly constructs a SubscribeOptions object with data_ == 0b00000000;
endpoint->subscribe("topicname", retain_handling::never); ///< Implicitly constructs a SubscribeOptions object with data_ == 0b00100000;
endpoint->subscribe("topicname", retain_handling::never | qos::exactly_once); ///< Implicitly constructs a SubscribeOptions object with data_ == 0b00100010;
```

**Comment by jonesmz** [comment]
If you want, we can also add some error checking:

```cpp
struct SubscribeOptions
{
    SubscribeOptions(retain_handling value) : data_(static_cast<std::uint8_t>(value)), has_retain_handling_(true) { };
    SubscribeOptions(rap value) : data_(static_cast<std::uint8_t>(value)), has_rap_(true) { };
    SubscribeOptions(nl value) : data_(static_cast<std::uint8_t>(value)), has_nl_(true) { };
    SubscribeOptions(qos value) : data_(static_cast<std::uint8_t>(value)), has_qos_(true) { };

    SubscribeOptions& operator|=(retain_handling value)
    {
        if(has_retain_handling_) { // throw exception here }
        has_retain_handling_ = true;
        data_ =| static_cast<std::uint8_t>(value);
        return *this;
    }
    SubscribeOptions& operator|=(rap value)
    {
        if(has_rap_) { // throw exception here }
        has_rap_ = true;
        data_ =| static_cast<std::uint8_t>(value);
        return *this;
    }
    SubscribeOptions& operator|=(nl value)
    {
        if(has_nl_) { // throw exception here }
        has_nl_ = true;
        data_ =| static_cast<std::uint8_t>(value);
        return *this;
    }
    SubscribeOptions& operator|=(qos value)
    {
        if(has_qos_) { // throw exception here }
        has_qos_ = true;
        data_ =| static_cast<std::uint8_t>(value);
        return *this;
    }

    retain_handler get_retain_handler() { return static_cast<retain_handler>(data_ & 0b00110000; }
    rap get_rap() { return static_cast<rap>(data_ & 0b00001000; }
    nl get_nl() { return static_cast<nl>(data_ & 0b00000100; }
    qos get_qos() { return static_cast<qos>(data_ & 0b00000011; }

    operator std::uint8_t() { return data_; }
    std::uint8_t data_;
    // Error checking logic. Maybe only when MQTT_DEBUG is defined.
    std::uint8_t has_retain_handling_ : 1;
    std::uint8_t has_rap_ : 1;
    std::uint8_t has_nl_ : 1;
    std::uint8_t has_qos_ : 1;
};
```

**Comment by jonesmz** [comment]
Finally, to support backwards compatibility with the existing code, we can have SubscribeOptions accept std::uint8_t as an argument as well.

```cpp
struct SubscribeOptions
{
    SubscribeOptions(std::uint8_t value) : data_(value) {};
    std::uint8_t data_;
};

**Comment by jonesmz** [comment]
Replaced by https://github.com/redboltz/mqtt_cpp/pull/387

**Pull request closed without merging**
