### PR TITLE
Rework a lot of the cmake configuration to use the cmake library link…

### PR DESCRIPTION
**Pull request by jonesmz**
…ing system instead of raw CXXFLAGS

### CODE REVIEW

**Comment by jonesmz** [comment]
Summary of changes:

- Use cmake's library settings functionality instead of raw CXX flag settings to configure dependencies.
- Use cmake's "generator expression" to simplify setting optional compile time flags
- Handle the header-file-include-dependency checking in a more robust way (I had problems running it on my machine before)
- Use the system supplied cmake on ubuntu
- Move to ubuntu bionic on travis
- Remove some unnecessary environment variables

**Comment by redboltz** [comment]
Sorry, I cancelled the build on azure by accident. Just re-ran.

**Comment by redboltz** [comment]
> Move to ubuntu bionic on travis

I forgot the reason but you said that bionic is too new and trusty is not so old.
Is the situation changed?

**Comment by jonesmz** [comment]
My requirement is that I can compile on OpenWRT 18.06.1, which uses GCC 7.3

We use ubuntu compiler repository to directly install gcc-7, so no problem.

The change to bionic was to access newer cmake.

I will see if xenial's cmake is good enough.

**Comment by jonesmz** [comment]
@redboltz 

Can you take a look at the azure-pipelines failure? I have no idea why it can't find boost-date-time.

**Comment by redboltz** [comment]
I don't have much time to check whole changes. But it seems that you removed `MQTT_LINK_LIBRARIES`. That causes the error I think.

**Comment by jonesmz** [comment]
> I don't have much time to check whole changes. But it seems that you removed MQTT_LINK_LIBRARIES. That causes the error I think.

The reason for removing MQTT_LINK_LIBRARIES is that mqtt_cpp_iface already has the full list of libraries that anything compiling against mqtt_cpp_iface needs to link against.

Manually constructing the list of libraries in a cmake variable is error prone, where using "TARGET_LINK_LIBRARIES()" is much more reliable.

**Comment by jonesmz** [comment]
I'm discontinuing work on this. Boost is clearly installed incorrectly on azure pipelines, as the cmake find_package integration with boost is finding the wrong boost root directory.

@redboltz I'd be happy to help you investigate this further, but I'm not able to spend any more time on it.

**Comment by jonesmz** [comment]
Well, I ended up finding a solution to the problem while working on something else.

This can be merged right away, the travis build has been passing for quite a while. and the recent changes have been only for azure.

But it's also fine if you want to wait for all of the builds to finish.

**Comment by jonesmz** [comment]
@redboltz Can you kill all but the most recent travis build?

**Comment by redboltz** [comment]
> @redboltz Can you kill all but the most recent travis build?

Done. I was at a business meeting.

**Comment by redboltz** [comment]
Thank you. Great work!

**Pull request merged**
