### PR TITLE
Converted subscription map from set to hash map

### PR DESCRIPTION
**Pull request by kleunen**
I changed the underlying storage of multiple_subscription_map from std::set to std::unordered_map. This improves the performance of the insert/delete operation and the map allows for updating a key in the map. The multiple_subscription_map now stores multiple key => value pairs per subscription. Insertion is changed as follows:

```C++
multiple_subscription_map<std::string, int> map; 
map.insert_or_update("a/b/c", "123", 0); // Insert
map.insert_or_update("a/b/c", "123", 1); // Update
map.erase("a/b/c", "123"); // Erase key
````

The find operation now gives the key and value as argument to the callback:
````C++
map.find("a/b/c", [](std::string const &key, int value) {

});
````
A hash and equal_to now needs to be defined for the key that is stored: 
````C++
struct sub_con_online_cref_hasher
{
    std::size_t operator()(sub_con_online_cref const& s) const noexcept;
};

struct sub_con_online_cref_equal_to
{
    bool operator()(sub_con_online_cref const& lhs, sub_con_online_cref const& rhs) const noexcept;
};

using sub_con_online_map = multiple_subscription_map<sub_con_online_cref, int, sub_con_online_cref_hasher, sub_con_online_cref_equal_to >;

std::size_t sub_con_online_cref_hasher::operator()(sub_con_online_cref const& s) const noexcept
{
    std::size_t result = 0;
    boost::hash_combine(result, s.get().con);
    boost::hash_combine(result, s.get().topic_filter);
    return result;
}

bool sub_con_online_cref_equal_to::operator()(sub_con_online_cref const& lhs, sub_con_online_cref const& rhs) const noexcept {
    return lhs.get().con == rhs.get().con && lhs.get().topic_filter == rhs.get().topic_filter;
}
````

This does change the interface a little bit. There is one optimization I would still like to make, if a subscription has very little subscribers (0 or 1), the unordered_map is quite an overhead. I would still like to optimize that for small number of subscriptions a boost::flat_map is used and for large number of subscriptions it is switched to the unordered_map

### CODE REVIEW

**Comment by redboltz** [comment]
In your example code, `value` is passed by value.

```cpp
map.find("a/b/c", [](std::string const &key, int value) {

});
```

Can I passed by non const reference as follows ?
I guess I can do.

```cpp
map.find("a/b/c", [](std::string const &key, int& value) {

});
```

**Comment by kleunen** [comment]
> Can I passed by non const reference as follows ?
> I guess I can do.
> 
> ```c++
> map.find("a/b/c", [](std::string const &key, int& value) {
> 
> });
> ```

Yes, that should be possible. But do realize find is not there to find a single registered subscription (a get operation), but rather, to find all subscriptions that match a certain published topic. I think you and I mixed this a little in the discussion we had. 

When you want to update the QoS for a single subscription, you should not have used find, but rather a get operation was required. We were focussing on the find, but this was not the right place.

**Comment by ogis-kondo** [comment]
> No, at the this is not possible

I can't accept it. The original problem is pass to non const reference. It is the most important thing.
It is not for QoS update. It is for deliver (publish (write access) to the session).

For QoS (and subopts) update on subscribe, I use insert(). It is completely different.

**Comment by redboltz** [comment]
> No, at the this is not possible

I can't accept it. The original problem is pass to non const reference. It is the most important thing.
It is not for QoS update. It is for deliver (publish (write access) to the session).

For QoS (and subopts) update on subscribe, I use insert(). It is completely different.

**Comment by kleunen** [comment]
> I can't accept it. The original problem is pass to non const reference. It is the most important thing.
> It is not for QoS update. It is for deliver (publish (write access) to the session).

ah ok, i understand. Than I will also add the find_and_modify, which will give you a modifyable reference.

**Comment by redboltz** [comment]
> > I can't accept it. The original problem is pass to non const reference. It is the most important thing.
> > It is not for QoS update. It is for deliver (publish (write access) to the session).
> 
> ah ok, i understand. Than I will also add the find_and_modify, which will give you a modifyable reference.

Ok I understand. No problem.
By the way, why do you prepare different function ?

**Comment by kleunen** [comment]
> By the way, why do you prepare different function ?

I was confused by the discussion, I understood that: 
- the insert operation does not allow updating the QoS of subscription, you would require: remove, update QoS, insert. I though you considered this a drawback
- i realized you could not modify the elements in the find operation, or call non-const methods

But I guess actually both issues were relevant. 

And I get annoyed by the time-complexity of the set O(log(N)) for insert/erase, I realized a unordered_map or unordered_set could provide O(1) insert/erase.

**Comment by kleunen** [comment]
````C++

struct my {
    void const_mem_fun() const {
        std::cout << "const_mem_fun()" << std::endl;
    }
    void non_const_mem_fun() {
        std::cout << "non_const_mem_fun()" << std::endl;
    }
};

BOOST_AUTO_TEST_CASE( test_multiple_subscription_modify ) {

    using mi_t = multiple_subscription_map<std::string, my>;
    mi_t map;
    map.insert_or_update("a/b/c", "123", my());
    map.insert_or_update("a/b/c", "456", my());

    map.modify("a/b/c", [](mi_t::container_t &container) {
        for(auto& i: container) {
            i.second.const_mem_fun();
            i.second.non_const_mem_fun();
        }
    });
}

**Comment by redboltz** [comment]
I don't think the problem is `std::set` and `std::unordered_map` difference.
unordered_map is not actually O(1). It is technically O(1) but there are hidden cost. e.g.) hash value calclation.

The point is `std::set` and `std::map` difference.
The value of `std::set` cannot update without removing from the container. So it only provides const reference.
On the other hand, the value of `std::map` **can update**. We can get the non const reference in the container.
On `std::map`, we can only get const reference of the Key. 

The point is separating Key and Value.

**Comment by kleunen** [comment]
> I don't think the problem is `std::set` and `std::unordered_map` difference.
> unordered_map is not actually O(1). It is technically O(1) but there are hidden cost. e.g.) hash value calclation.

Yes, and unordered_map has higher memory consumption, it allocates every entry seperately. boost::flat_map uses a contiguous allocation, much lower memory consumption. So that is why I would like to use boost::flat_map when storing only small number of connections at same subscription.

**Comment by kleunen** [comment]
> hash value calclation

Yes, hash calculation is now done on string. This can still be improved, maybe calculate hash based on size_t session_id ?
````
// Hash and equal_to required for storing sub_con_online and sub_con_offline in subscription map
inline std::size_t test_broker::sub_con_online_cref_hasher::operator()(test_broker::sub_con_online_cref const& s) const noexcept
{
    std::size_t result = 0;
    boost::hash_combine(result, s.get().con);
    boost::hash_combine(result, s.get().topic_filter);
    return result;
}

inline std::size_t test_broker::sub_con_offline_cref_hasher::operator()(test_broker::sub_con_offline_cref const& s) const noexcept
{
    std::size_t result = 0;
    boost::hash_combine(result, s.get().client_id);
    boost::hash_combine(result, s.get().topic_filter);
    return result;
}

**Comment by redboltz** [comment]
> I don't think the problem is `std::set` and `std::unordered_map` difference.
> unordered_map is not actually O(1). It is technically O(1) but there are hidden cost. e.g.) hash value calclation.
> 
> The point is `std::set` and `std::map` difference.
> The value of `std::set` cannot update without removing from the container. So it only provides const reference.
> On the other hand, the value of `std::map` **can update**. We can get the non const reference in the container.
> On `std::map`, we can only get const reference of the Key.
> 
> The point is separating Key and Value.

https://wandbox.org/permlink/3tGzdUrLJPBy9tZU

```cpp
#include <map>
#include <set>

int main() {
    std::set<int> s;
    std::map<int, int> m;

    s.emplace(1);
    // *s.begin() = 2; // cannot write to const reference
    
    m.emplace(1, 2);
    // m.begin()->first = 3; // cannot write to const reference
    m.begin()->second = 4; // an write to value. can provide non const reference for the value in the container
}
```

See the last line. You can pass the non const reference of the value without remove/insert form/to the container.
It is the key feature.

**Comment by redboltz** [comment]
> > hash value calclation
> 
> Yes, hash calculation is now done on string. This can still be improved, maybe calculate hash based on size_t session_id ?
> 
> ```c++
> // Hash and equal_to required for storing sub_con_online and sub_con_offline in subscription map
> inline std::size_t test_broker::sub_con_online_cref_hasher::operator()(test_broker::sub_con_online_cref const& s) const noexcept
> {
>     std::size_t result = 0;
>     boost::hash_combine(result, s.get().con);
>     boost::hash_combine(result, s.get().topic_filter);
>     return result;
> }
> 
> inline std::size_t test_broker::sub_con_offline_cref_hasher::operator()(test_broker::sub_con_offline_cref const& s) const noexcept
> {
>     std::size_t result = 0;
>     boost::hash_combine(result, s.get().client_id);
>     boost::hash_combine(result, s.get().topic_filter);
>     return result;
> }
> ```

I don't decide yet. But client_id is a good candidate of the key if I use unordered_map.

**Comment by redboltz** [comment]
Please check https://wandbox.org/permlink/0d5Oh4IQu4qV6wzR

```cpp
#include <map>
#include <string>
#include <iostream>
#include <cassert>

template <typename Key, typename Value, typename Cont = std::map<Key, Value>>
struct sub_map {

    template <typename K, typename V>
    std::pair<typename Cont::iterator, bool> insert(K&& k, V&& v) {
        auto it = c.find(k);
        if (it == c.end()) {
            auto it_ret = c.emplace(std::forward<K>(k), std::forward<V>(v));
            assert(it_ret.second);
            return std::make_pair(it_ret.first, true);
        }
        else {
            it->second = std::forward<V>(v);
            return std::make_pair(it, false);
        }
    }
    
    template <typename Callback>
    void find(Callback cb) {
        for (auto& elem : c) {
            // elem.second is non const
            cb(elem.first, elem.second);
        }
    }
    Cont c;
};

struct session {
    std::string client_id;
    void publish() {
        std::cout << "publish" << std::endl;
    }
};

struct sub_elem {
    std::reference_wrapper<session> s;
    int qos;
};

inline bool operator<(sub_elem const& lhs, sub_elem const& rhs) {
    return lhs.s.get().client_id < rhs.s.get().client_id;
}

int main() {
    session s1 { "cid1" };
    
    sub_map<std::string, sub_elem> m;
    
    m.insert(s1.client_id, sub_elem { s1, 1 }); // insert qos1
    m.insert(s1.client_id, sub_elem { s1, 2 }); // update qos2
    m.find(
        [](std::string const& key, sub_elem& sub) {
            std::cout << "client_id:" << key << " QoS:" << sub.qos << std::endl;
            sub.s.get().publish();
        }
    );
        
}
```

It is a concept model of `std::map` or `std::unordered_map` version.

**Pull request closed without merging**
