### PR TITLE
Added disconnect timeout for client.

### PR DESCRIPTION
**Pull request by redboltz**

### CODE REVIEW

**Comment by kleunen** [comment]
The interface looks good like this. It may take a while before I am able to test the code. But I see you added a unit test to test the functionality.

**Comment by kleunen** [comment]
I do have one remark, but maybe this is related to other code as well:

Why use size_t as time and use milliseconds as base? 
Why not use 'boost::posix_time::time_duration' and then the user can call:

```C++
disconnect(boost::posix_time::milliseconds(1000))
````
or:
```C++
disconnect(boost::posix_time::seconds(1))
```

That way there is no unclarity about the interface: the user can specify the time duration in milliseconds or seconds and does not have to lookup what time unit the library expects.

**Comment by redboltz** [comment]
I agree with you. I updated the type.
And added some more fix and tests.

**Comment by kleunen** [comment]
Hello redboltz, you closed this issue, but I was thinking it may be a good idea to give a default value for the timeout argument. I guess many users don't want to bother thinking this timeout or do not know what a good value for the timeout would be. So I would set it to a timeout of 5 seconds for example (or whatever you think is a good value), to give the indication as the developer of the library you think this is a reasonable value.

**Comment by redboltz** [comment]
I'd like to keep the original behavior. If `disconnect()` is called with no argument, that means no timeout. So I implemented the following overload. 
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/client.hpp#L315
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/client.hpp#L341

I think that appropriate timeout value is different each environment. Users have a change to think about the timeout and their environment. I think that it is not so bad.

**Comment by kleunen** [comment]
Ah yes, that sounds good :)

**Pull request merged**
