### PR TITLE
Fixes 433: Don't bother with MQTT_NS::optional for puback/pubrel/pubrec/pubcomp reason codes

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by redboltz** [comment]
I have a question.

On MQTTv5, if reason_code is success and no properties, what is expected sending packet?

puback example

1. Fixed Header 0x42 (puback and remaining length2) and packet_id
2. Fixed Header 0x43 (puback and remaining length3), packet_id, and reason_code 0.
3. User can choose 1or2.

I think that 1 or 3 is good. If it is complicated to implement 3, then 1 is acceptable.
What do you think?

And which way the PR is going?

**Comment by jonesmz** [comment]
> On MQTTv5, if reason_code is success and no properties, what is expected sending packet?

If reason_code is success, and no properties, the packet should have

Fixed Header 0x42 (puback and remaining length2) and packet_id

> The Reason Code and Property Length can be omitted if the Reason Code is 0x00 (Success) and there are no Properties. In this case the PUBACK has a Remaining Length of 2.

This saves on serialization, network bandwidth, and also deserialization on the server.

It sounds like you want to support including the reason_code and empty properties, if the end-user wants to?

I suppose I don't understand why anyone would ever want to include the extra data in the packet if they didn't need to.

**Comment by redboltz** [comment]
> I suppose I don't understand why anyone would ever want to include the extra data in the packet if they didn't need to.

Ok, basically I agree with you.

It is different topic that if mqtt_cpp **receives** puback packet that has fixed Header 0x43 (puback and remaining length3), packet_id, and reason_code 0, then it should be treated as a valid packet.
In order to test the behavior above, I think that it is (very little) valuable to have sending packet as the pattern 2.
But I don't strongly want to have it. Normal user likes efficient packet sending.

**Comment by jonesmz** [comment]
> It is different topic that if mqtt_cpp receives puback packet that has fixed Header 0x43 (puback and remaining length3), packet_id, and reason_code 0, then it should be treated as a valid packet.

Yes, agree.

**Comment by jonesmz** [comment]
> In order to test the behavior above, I think that it is (very little) valuable to have sending packet as the pattern 2.
>But I don't strongly want to have it. Normal user likes efficient packet sending.

What do you think of a compile-time option?

We can also make it a constructor parameter for the `v5::*_message` objects, so that it can be done in unit tests, but normally it does not send extra.

**Comment by redboltz** [comment]
> What do you think of a compile-time option?
> 
> We can also make it a constructor parameter for the v5::*_message objects, so that it can be done in unit tests, but normally it does not send extra.

I think that it is a good idea. Mostly debug purpose. Compile time option is suitable and easy to implement.

Could you add the option to the PR?

**Comment by redboltz** [comment]
Thank you for updating.

**Pull request merged**
