### PR TITLE
Use SYSTEM in target_include_directories()

### PR DESCRIPTION
**Pull request by CodeFinder2**
This allows one to use/compile this library in a project where stricter compiler settings
(like `-pedantic` and `-Werror`) are in use. *gcc* and *clang* ignores such issues in all
system includes and as a consequence of adding `SYSTEM` to
`target_include_directories()`, the headers of this library are treated as system includes
as well.

Thanks for considering! :-)

### CODE REVIEW

**Comment by redboltz** [comment]
@CodeFinder2 , mqtt_cpp satisfies the following warning flags.
https://github.com/redboltz/mqtt_cpp/blob/1eaadab575f15d7e645c9cb699e7e3eeba7587c6/.github/workflows/gha.yml#L69
`-pedantic -Werror` are satisfied.
The compiler version on the CI is not up to date. So some of warnings would be reported as error on some envronment. But it this case, the warning should be fixed. If you find such warnings, then please report issue and create a pull request to solve it.
(Sometimes we need to use warning suppression pragma)

I'm not an expert of cmake but SYSTEM seems to be too much relaxed mqtt_cpp's checking.

**Comment by redboltz** [comment]
One more comment.
Why do you remove the following line?
https://github.com/redboltz/mqtt_cpp/pull/832/files#diff-f15f7409d37485ed889fc8730c1f63d6570e55cfb27a4ee9dc7760014a79a739L39

**Comment by CodeFinder2** [comment]
Hi @redboltz , thanks for your quick reply and sorry for answering this late!

We're using an older version of your library as a Git submodule, included as part of a CMake build system and that creates warnings/errors with `-pedantic -Werror`. Due to issues with Boost, we cannot simply use your latest version and that's why I suggested these changes. However, regardless of our setup, I think it would be a good choice to be able to declare your library includes as `SYSTEM` includes since as a user of this library, one does not have control over the code and newer compiler versions may output warnings in the future that are currently not fixed.

But finally, it is of course up to you and I also understand that it makes your own includes (as a library dev) too relaxed. I don't know how to avoid this in CMake (except for creating a "dummy target" or something like that).

Removing the 2nd line was by accident, sorry! I would undo this change if you agree to merge this. ;-)

**Comment by jonesmz** [comment]
I recommend against making this change as its currently done.

1) As redboltz points out, warnings should be fixed, not covered up.
2) Cmake's support for SYSTEM is done very poorly.

The way SYSTEM works in cmake is that it essentially embodies the concept of a header file / directory controlled by the operating system. There are hints in the documentation that it also surpresses some of the various configuration-time dependency logic that cmake uses to ensure generated headers are present, but I didn't find any evidence of that in my use of cmake so far.

However, because cmake requires that you designate the include directory as SYSTEM in the place where it's initially linked to a target, and provides no mechanism to say target A depends on target B, but target B should treat it's includes as normal, and target A should treat target B's public / interface includes as SYSTEM (or for MSVC, as 3rdparty includes), you're left forcing projects to have an all or nothing approach to header management.

For example, many projects, such as the one that i was working on (and no longer am anymore due to job reasons) that initially brought me into working on mqtt_cpp, do not use SYSTEM includes specifically so that underlying warnings in 3rd party libraries could be identified and repaired. Many of the improvements i made to mqtt_cpp and other unrelated libraries came directly from *not* using SYSTEM. It's in mqtt_cpp's best interest to ensure that any warnings are very annoying to consumers of the project to get pull requests.

So my recommendation is that instead of making the include directories SYSTEM for all consuming projects, you should define a *new* interface library mqtt_cpp_system or similar that is exactly the same as mqtt_cpp, but with the include directories marked as SYSTEM.

In this way, only projects that *want* the includes marked as SYSTEM will be forced to accept that.

I would argue that realistically this should be fixed directly by CMake, as the current support for this is woefully under-achieving. But that's like arguing with a tree. Sometimes the squirrels give you an acorn, and sometimes they laugh at you, and sometimes there are no squirrels.

**Comment by redboltz** [comment]
@CodeFinder2 
I don't agree to merge the PR. mqtt_cpp is NOT a SYSTEM library. And SYSTEM approach is not an essential fix the issue.

But I can tell you how to treat the problem well on your environment.
mqtt_cpp is a header-only library, so you don't need to build the library. Just adding include path.
You can set the following parameters to OFF, then the build step is disabled.
(I updated the wiki https://github.com/redboltz/mqtt_cpp/wiki/Config#build-control-cmake-options)
https://github.com/redboltz/mqtt_cpp/blob/07c70974c481809e8f1aff0725a77a83c62c8101/CMakeLists.txt#L10-L11
So mqtt_cpp building process doesn't report warnings any more (because it doesn't run).

I guess that in **your** application code is built using relax options. If mqtt_cpp header files reports warnings in **your** build project, you can add pragma as follows:

your_application.cpp

```cpp
#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
#endif // defined(__GNUC__)

#include <mqtt_client_cpp.hpp>
#include <mqtt/setup_log.hpp> // if you want to use typical logging setup 

#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif // defined(__GNUC__)
```

This is `implicit-fallthrough` warning suppression example.

**Comment by CodeFinder2** [comment]
Thanks for all your efforts (also @jonesmz ). I completely agree to not merge this PR, sorry for the noise!

I am not building your library anyways (since I didn't need the examples and tests). I took this conversation as a kick-off for porting our project to the newest version and it seems to work fine. And it also compile flawlessly with `-pedantic` and `-Werror`, so this PR is needless anyway. :-)

I have another question regarding capturing `std::shared_ptr` in a lambda function: do you want me to open a new issue for this (since it is not related to this in any way) or may I ask here? In short: isn't [this](https://floating.io/2017/07/lambda-shared_ptr-memory-leak/) a problem here, for instance, in your examples [here](https://github.com/redboltz/mqtt_cpp/blob/master/example/no_tls_client.cpp#L28) and [there](https://github.com/redboltz/mqtt_cpp/blob/master/example/no_tls_client.cpp#L41)?

Thanks again for your quick support!

**Comment by jonesmz** [comment]
You should open new issues for new questions.


That being said, the article you linked seems to be mostly about FUD. mqtt_cpp does not inherently have the described problem, and the examples from mqtt_cpp that you li led are unrelated to the article because the examples use references in the lambda capture.

**Pull request closed without merging**
