### PR TITLE
Add new publish_options struct, similar to subscribe_options struct. Remove ***_dup functions.

### PR DESCRIPTION
**Pull request by jonesmz**
I'd like some feedback on the names of the new items. I'm not happy with the names I picked for e..g `enum class dup` or `enum class publish_retain`

### CODE REVIEW

**Comment by jonesmz** [comment]
For: https://github.com/redboltz/mqtt_cpp/issues/426

**Comment by redboltz** [comment]
> I'd like some feedback on the names of the new items. I'm not happy with the names I picked for e..g enum class dup or enum class publish_retain

I think that the enumerator `yes`/`no` is good. It is apparently better than  something like `dup`/`no_dup`.

Both enum class name `dup` and `publish_retain` are only for publish. I think that the naming rule should be consistent. `publish_dup` and `publish_retain`, or `dup` and `retain`. I prefer to the latter because they are short. `retain` might conflict existing name, but I guess that it can be solved.

**Comment by jonesmz** [comment]
Assuming CI passes, I believe I've addressed all your concerns.

**Comment by jonesmz** [comment]
Ci failed with

Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)


Please retrigger

**Comment by redboltz** [comment]
> Assuming CI passes, I believe I've addressed all your concerns.

It seems that you are using `publish_dup` and `publish_retain`.

I commented that `dup` and `retain` (latter) are better because of they are short.

See

>> Both enum class name dup and publish_retain are only for publish. I think that the naming rule should be consistent. publish_dup and publish_retain, or dup and retain. I prefer to the latter because they are short. retain might conflict existing name, but I guess that it can be solved.

Could you replace `publish_dup` and `publish_retain` with `dup` and `retain` ?

**Comment by jonesmz** [comment]
How to solve the name conflict with retain?

**Comment by ogis-kondo** [comment]
> How to solve the name conflict with retain?

The existing variable names `retain` can be replaced with `r` or `retain_val`.

The following enumerator `retain` can be replaced with `retain_as_published`.

```cpp
enum class rap : std::uint8_t
{
    dont = 0b00000000,
    retain = 0b00001000,
};
```

If I am missing something more, please let me know.

**Comment by redboltz** [comment]
> How to solve the name conflict with retain?

The existing variable names `retain` can be replaced with `r` or `retain_val`.

The following enumerator `retain` can be replaced with `retain_as_published`.

```cpp
enum class rap : std::uint8_t
{
    dont = 0b00000000,
    retain = 0b00001000,
};
```

If I am missing something more, please let me know.

**Comment by jonesmz** [comment]
Alright, that should do it. Not as many name conflicts as I thought there would be.

**Comment by redboltz** [comment]
Thank you for updating. The code is nice! It seems that OpenSSL error still happen on osx. I re-triggered several times but I got the same error.

**Comment by jonesmz** [comment]
Maybe Github Actions may help with openssl problem, and build time problem.

**Comment by redboltz** [comment]
> Maybe Github Actions may help with openssl problem, and build time problem.

Ah, it's #550 you reported. It seems that I need to study how it works.

I will merge the PR before introducing Github Actions.
The errors aren't caused by the change in the PR. 
(I've triggered one of old master build and got the same error https://travis-ci.org/redboltz/mqtt_cpp/jobs/607471763)

After I merged the PR, I will try solving OpenSSL error on osx.

**Pull request merged**
