### PR TITLE
Fixed #281.

### LINKED ISSUE #281: Want to be able to use operator<< (or similar) with correlation_data_ref and friends.
I want to be able to use the properties with std::ostream.

An easy way to provide this is to have a template function:

```
template<typename T>
T & operator<<(T& ostr, correlation_data)
{
    ostr << correlation_data.val();
    return ostr;
}
```

### PR DESCRIPTION
**Pull request by redboltz**
Added stream output operators for properties.

### CODE REVIEW

**Comment by jonesmz** [comment]
You weren't able to make the stream operators generic? I'm surprised.

Could I ask what prevented it from working?

**Comment by redboltz** [comment]
There are some exceptions:

* `maximum_qos` requires `static_cast<int>` because actual value is 0x00..0x02.
* `content_type` prints "binary" or "string" but actual value is internal enum.
* `user_property" prints "key:val".

And non restricted template has bad side-effect. So I need to some SFINAE.
I think that all of properties should have the same internal type for SFINAE. But those three exceptions don't use it. Just non-template overloads.
I feel some non elegant flavor. So I wrote the operators individually.

If you come up with more elegant and consistent approach, please let me know, I will update the PR.

**Comment by jonesmz** [comment]
I understand.

I'll let you know if I think of a better way, but I wouldn't wait on me to submit this. It can always be improved later.

**Comment by redboltz** [comment]
I updated t tag based generic dispatch. To be honest, I'm not satisfied this approach.
I wanted to `key()`, `val()` member function existence based, and its return type based approach.
But I couldn't find a way.
https://stackoverflow.com/questions/56663584/how-to-check-callable-member-function-existence-of-derived-class

**Comment by jonesmz** [comment]
To do detection like that, i typically make a type-trait class like this

```
template<typename CLASS_T>
struct detect_key_function
{
    template<typename FOO_T>
    auto check_for_key(FOO_T* p) -> decltype(std::declval<FOO_T>().key(), std::true_type());
    std::false_type check_for_key(...);

    using type = decltype(check_for_key<CLASS_T>(nullptr));
}
```

Though, note that I'm typing that from memory, so it probably doesn't work without some tweaking.

**Comment by redboltz** [comment]
I add `static` to `check_for_key` then the code is compiled.

But I got compile error, not static assertion failure non existing case.
https://wandbox.org/permlink/JWsw1MngGXwCaJCh

For existing case, it works well.
https://wandbox.org/permlink/RDgl8uw6QsKkAa4w

**Comment by jonesmz** [comment]
Hrmm. At my last job, I wrote variations of this pattern about 10 times... but I don't have access to that code anymore, and I just simply don't remember all of the details...

This stackoverflow post is where I got my original information behind this pattern.

Maybe it'll be useful to you?

**Comment by redboltz** [comment]
I've checked https://stackoverflow.com/questions/32518635/how-to-detect-that-a-member-function-has-specific-function-taking-specific-argu.

But I got the same result of Boost.TTI.
See https://wandbox.org/permlink/VXCn4e3eHDHyIKEo

**Comment by redboltz** [comment]
https://wandbox.org/permlink/No7tA2OCQtMjqgD2

```cpp
#include <iostream>
#include <string>
#include <type_traits>

struct prop_size {
    using has_val = void;
    std::size_t val() const { return 123; }
};

struct prop_max_val : prop_size {
};

struct prop_qos {
    using has_val = void;
    std::uint8_t val() const { return 2; }
};

struct prop_ct {
    enum payload_format {
        binary,
        string
    };
    payload_format val() const { return binary; }
};

struct prop_kv {
    using has_key_and_val = void;
    int key() const { return 456; }
    int val() const { return 789; }
};

template <typename Property>
inline
typename std::enable_if<
    !std::is_same_v<
        typename std::result_of<
            decltype(&Property::val)(Property)
        >::type,
        std::uint8_t
    >
    &&
    !std::is_same_v<
        typename std::result_of<
            decltype(&Property::val)(Property)
        >::type,
        prop_ct::payload_format
    >
    ,
    std::ostream&
>::type
operator<<(std::ostream& o, Property const& p) {
    o << p.val();
    return o;
}

template <typename Property>
inline
typename std::enable_if<
    std::is_same_v<
        typename std::result_of<
            decltype(&Property::val)(Property)
        >::type,
        std::uint8_t
    >,
    std::ostream&
>::type
operator<<(std::ostream& o, Property const& p) {
    o << static_cast<int>(p.val());
    return o;
}

template <typename Property>
inline
typename std::enable_if<
    std::is_same_v<
        typename std::result_of<
            decltype(&Property::val)(Property)
        >::type,
        prop_ct::payload_format
    >,
    std::ostream&
>::type
operator<<(std::ostream& o, Property const& p) {
    o << (p.val() == prop_ct::binary ? "binary" : "string");
    return o;
}



#if 0

// This is a problem

template <typename Property>
inline
typename std::enable_if<
    std::is_same_v<
        typename std::result_of<
            decltype(&Property::key)(Property)
        >::type,
        decltype(std::declval<Property const>().key())
    >
    &&
    std::is_same_v<
        typename std::result_of<
            decltype(&Property::val)(Property)
        >::type,
        decltype(std::declval<Property const>().val())
    >,
    std::ostream&
>::type
operator<<(std::ostream& o, Property const& p) {
    o << p.key() << ':' << p.val();
    return o;
}

#endif

int main() {
    std::cout << "max_val : " << prop_max_val() << std::endl;
    std::cout << "prop_qos: " << prop_qos() << std::endl;
    std::cout << "prop_ct : " << prop_ct() << std::endl;
    std::cout << "prop_kv : " << prop_kv() << std::endl;
}
```

This is `std::result_of` approach. It works well  excepts key_val. Only val is printed.

If `#if 0` part is enabled, compile errors happen.

NOTE: `std::resulf_of` should be `std::invoke_result` in C++17.

**Pull request merged**
