### PR TITLE
Precompiled header build

### PR DESCRIPTION
**Pull request by kleunen**
Build time seems to go from 30 minutes to 25 minutes using PCH, so a small improvement

### CODE REVIEW

**Comment by kleunen** [comment]
I think the linking is also a significant part in time of the building

**Comment by redboltz** [comment]
It seems that you added preconpiled headers but also added linker option.
I created #777 that contains only liker option.
Then, I ran CI several times. In addition, I re-ran the master CI.

The master took 27m 40s at the last try.
https://github.com/redboltz/mqtt_cpp/actions/runs/451943212
It seems that the master takes around 30munutes.

#777 took 29m 41s at the last try.
https://github.com/redboltz/mqtt_cpp/actions/runs/453631994
It seems that #777 takes around 30munutes.

#776 took  28m 42s at the last try.
https://github.com/redboltz/mqtt_cpp/actions/runs/453035753
It seems that #777 takes around 25munutes as you reported.

By the way
https://cmake.org/cmake/help/git-stage/command/target_precompile_headers.html
It seems that `target_precompile_headers` has been introduced since cmake 3.16.0.
So, CMAKE_MINIMUM_REQUIRED should be updated.

There are many place that defines CMAKE_MINIMUM_REQUIRED.
https://github.com/redboltz/mqtt_cpp/blob/master/CMakeLists.txt#L1
https://github.com/redboltz/mqtt_cpp/blob/master/test/CMakeLists.txt#L7
https://github.com/redboltz/mqtt_cpp/blob/master/test/system/CMakeLists.txt#L7
https://github.com/redboltz/mqtt_cpp/blob/master/test/unit/CMakeLists.txt#L7

I don't know much about MAKE_MINIMUM_REQUIRED. Should MAKE_MINIMUM_REQUIRED be placed only the top CMakeLists.txt ? If it is, MAKE_MINIMUM_REQUIRED in sub directory should be removed.
What do you think ?

After you fixed MAKE_MINIMUM_REQUIRED, I will merge #776 and close #777.

I don't know much about Github Actions caching mechanism and pre compiled hreaders. 
You said that the current PCH is reused on multiple translation units (cpp files). But I guess that it is shared for each build groups. (macos 0..4, linux 0..7).

Github Actions has caching mechasism.
https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows
Can we use it accross the different build groups ?
I guess that it is impossible if the compiler options (preprosessor macros definition) are different. It that right ?

It seems that PCH works for the different template instantiation (I don't know how it works). How about preprosessor macros?

**Comment by jonesmz** [comment]
You guys probably want to use extern templates to cut down on compile times, more than precompiled headers, really.

**Comment by kleunen** [comment]
The precompiled headers just keeps the state after the includes. So I include: 
mqtt_client_cpp.hpp 
mqtt_server_cpp.hpp

And the state is kept after these two includes. Any defines for options you do before including these two headers should always be the same. For example at a later point you can not redefine MQTT_USE_LOG and include again: 
mqtt_client_cpp.hpp 
mqtt_server_cpp.hpp

It won't work, you can not change any macros in the pre-compiled header. 

The github actions just stores and restores a directory on the github runner server. So if I install and build openssl to
{{ runner.temp }}/opensslThe github action can tar.gz this directory and restores it on a subsequent run on the server, such that you don't have to reconfigure and build openssl again. 

Considering runtime, with the precompiled header I got the build system to run in 30 minutes including the windows builds on Github action. So I think it would be worthwile to include the github windows build, such that the azure build does not need to be maintained. The linker option is not needed, i tried this, but it makes no difference. 

I kind of agree with @jonesmz, the pre-compiled header is a patch solution, also extern templates are a temporary solution. I think in the long run, modules will be a much better solution when they become more widely available. But note that you can not use macro's to define behaviour in modules.

**Comment by kleunen** [comment]
> The master took 27m 40s at the last try.
> https://github.com/redboltz/mqtt_cpp/actions/runs/451943212
> It seems that the master takes around 30munutes.
> 
> #777 took 29m 41s at the last try.
> https://github.com/redboltz/mqtt_cpp/actions/runs/453631994
> It seems that #777 takes around 30munutes.
> 
> #776 took 28m 42s at the last try.
> https://github.com/redboltz/mqtt_cpp/actions/runs/453035753
> It seems that #777 takes around 25munutes as you reported.

Yes, I think the precompiled header has the most benefit on windows. On linux, I sometimes see longer compile times with PCH, sometimes lower. So I don't think there is much benefit there.

**Comment by kleunen** [comment]
Again a commit from the master branch is included, i don't understand why this is.

**Comment by redboltz** [comment]
The older PR is lost by forced push.
And the current PR contains windows build on Github Actions.
It is not expected one.
I just expect that the original PR and MAKE_MINIMUM_REQUIRED updates.

> Yes, I think the precompiled header has the most benefit on windows. On linux, I sometimes see longer compile times with PCH, sometimes lower. So I don't think there is much benefit there.

But if PCH doesn't provide expected speed up, I will simply close #773 #776 #777 .
Windows builds are not bottle neck, so far.

**Comment by kleunen** [comment]
Well, PCH can be convenient if you are developing on windows, like me :)

I do notice a very significant speed up when working on the examples with recompiling. So when you use the headers, it is convenient to have the PCH.

**Comment by redboltz** [comment]
> Well, PCH can be convenient if you are developing on windows, like me :)
> 
> I do notice a very significant speed up when working on the examples with recompiling. So when you use the headers, it is convenient to have the PCH. You can always make the default to be OFF.

Ok, Adding PCH options (by default OFF, and on CI ON) is nice to have. I will merge it.
But the current PR is something different.

> Again a commit from the master branch is included, i don't understand why this is.

If you stuck on something weird on this PR, you can create another PR that contains PCH option and MAKE_MINIMUM_REQUIRED . (It doesn't contain Windows Builds on GithubActions)

**Comment by kleunen** [comment]
No wait, don't merge yet!

**Comment by kleunen** [comment]
Ok, i will update the MAKE_MINIMUM_REQUIRED. But also, we should decide about the target of the PCH. Because now I use an empty "precomp.cpp" file. Both should we make this target to be the broker ?

**Comment by redboltz** [comment]
> No wait, don't merge yet!

Ok. I don't merge it. 

> Ok, Adding PCH options (by default OFF, and on CI ON) is nice to have. I will merge it.

Maybe my English was wrong. I wanted to say I will merge it **after some fix** :)

**Comment by redboltz** [comment]
> Ok, i will update the MAKE_MINIMUM_REQUIRED. But also, we should decide about the target of the PCH. Because now I use an empty "precomp.cpp" file. Both should we make this target to be the broker ?

What do you mean?   Does `precomp.cpp` have problem? 

It seems that `precomp.cpp` is not empty.

```cpp
#include <mqtt_client_cpp.hpp>
#include <mqtt_server_cpp.hpp>

int main()
{
    return 0;
}
```

I used to tried PCH (and cotire) but I couldn't get expected speedup and gave up it. 
So I don't have much about PCH.

**Comment by kleunen** [comment]
It is not really empty, but it doesn't really do anything. It is like a no-op application, just to get the PCH working. So it kind of bothers me this file should be in the repository. It is a style thing, i have a personal distaste this file has to be there, and the rules in the CMakeLists.txt, just to get the PCH working. 

https://github.com/redboltz/mqtt_cpp/pull/776/commits/e52b54cbf02ca13d379bd653e48d61e6343f67d3#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR142-R157

**Comment by redboltz** [comment]
> It is not really empty, but it doesn't really do anything. It is like a no-op application, just to get the PCH working. So it kind of bothers me this file should be in the repository. It is a style thing, i have a personal distaste this file has to be there, and the rules in the CMakeLists.txt, just to get the PCH working.
> 
> [e52b54c#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR142-R157](https://github.com/redboltz/mqtt_cpp/commit/e52b54cbf02ca13d379bd653e48d61e6343f67d3#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR142-R157)

Thank you for elaborating. I understand it is a style thing. Having `precomp.cpp` is good for me. But root directory is not so beautiful. How about `helper/precomp.cpp` or `util/precomp.cpp` ?
I like `helper/precomp.cpp`.

**Comment by kleunen** [comment]
helper/precomp.cpp is ok. But the target should still be in top level cmakelist

**Comment by redboltz** [comment]
> helper/precomp.cpp is ok. But the target should still be in top level cmakelist

I think that it is an acceptable point of compromise.

I think that the PR is ready to merge.

**Comment by kleunen** [comment]
I think we should try extern templates also. So please wait with merge

**Comment by redboltz** [comment]
Ok. No problem. Take your time.

Personally, my priority is implementing new functionality and modulize sdk part. Environment related issue is lower priority than them. The current compile times is acceptable for me.
However, the compile times speed up techniques are interesting. I will learn from your efforts :)

**Comment by jonesmz** [comment]
As I elaborated on in other comments on other issues, i intended to investigate using a different way of handling the sockets to support using the Boost.Asio coroutine support (Not C++20 coroutines, but the boost version that's implemented with macros) instead of using template functions that template based on an enum state machine, as well as removal of the boost type erasure library.

Doing that would require re-jiggering the way the low level socket wrapper classes work, but I believe that the end-result would compile substantially faster, due to a very large reduction in template instantiations.

I don't really want to get too deep into the weeds on that, and I can't really contribute much code to mqtt_cpp anymore because I have changed jobs and no longer use mqtt_cpp, but I really do recommend trying to take a look at doing some re-architecturing along those lines.

**Comment by kleunen** [comment]
I think the linux build is actually ignoring the precompiled header, because for the unit test compile the defines are different. So I guess it is silently ignoring the precompiled header.

**Comment by kleunen** [comment]
Best of wishes for 2021, 

it seems the current PR is incorrect, the test and examples use different command lines. So actually they should use different precompiled headers. With exactly the same command line as the cpp file that uses the header. I looked at using extern templates, compiling them in a shared library. But this gives no speed up linux or windows. 

Maybe just leave this for now, adding features is more important.

**Pull request closed without merging**
