### PR TITLE
Added test for move only value types.

### PR DESCRIPTION
**Pull request by redboltz**

### CODE REVIEW

**Comment by redboltz** [comment]
@kleunen , I got problems when I integrate subscription_map to test_broker.
It seems that the value type of subscription_map has too much implicit requirement.
I think that the container should support move constructible only classes.
See https://wandbox.org/permlink/vBcYdeRJSMTcNNOp

Could you update subscription_map to support move constructible only classes?

I just added tests for move only types in the #709. Could you write a PR against #709 ?

**Comment by kleunen** [comment]
But it seems you even deleted the assignment? This should be available right?

```C++
    struct my {
        my() = delete;
        my(int) {}
        my(my const&) = delete;
        my(my&&) = default;
        my& operator=(my const&) = delete;
        my& operator=(my&&) = delete; // Assignment also deleted, why ?
        ~my() = default;
    };

**Comment by redboltz** [comment]
> But it seems you even deleted the assignment? This should be available right?
> 
> ```c++
>     struct my {
>         my() = delete;
>         my(int) {}
>         my(my const&) = delete;
>         my(my&&) = default;
>         my& operator=(my const&) = delete;
>         my& operator=(my&&) = delete; // Assignment also deleted, why ?
>         ~my() = default;
>     };
> ```

Yes, I believe that containers in standard library don't require move assignable **in the library**.
But as you mentioned, test_broker usecase requires copy or move assignable. It is application code (test_broker code).

For example, https://wandbox.org/permlink/00D4zCmljoSiih8Q should be stored by subscription_map. Off course, the application operation is limited. e.g. `c.find("C")->second = something`.

**Comment by kleunen** [comment]
> Yes, I believe that containers in standard library don't require move assignable **in the library**.
> But as you mentioned, test_broker usecase requires copy or move assignable. It is application code (test_broker code).

Ok. But then if the data type is not move assignable or copy assignable, you can not update an entry. So you would need a separate insert, which does not attempt an update. 

Also the unordered_map is not updatable, if data type is not move assignable or copy assignable. 

Is that OK ?

**Comment by redboltz** [comment]
> > Yes, I believe that containers in standard library don't require move assignable **in the library**.
> > But as you mentioned, test_broker usecase requires copy or move assignable. It is application code (test_broker code).
> 
> Ok. But then if the data type is not move assignable or copy assignable, you can not update an entry. So you would need a separate insert, which does not attempt an update.
> 
> Also the unordered_map is not updatable, if data type is not move assignable or copy assignable.
> 
> Is that OK ?

Ah, the current interface is insert_or_update(). Hmm..., I should permit subscription_map depend on the value type is assignable to keep the current interface.
Ok, let's add a requirement for value_type. It should move or copy assignable.
Please remove non move assignable test case.

> Also, The STL allows insertion of a pair (pair<key, value>), which allowes moving in the complete <key, value> pair moving in the map. Should we add this ? Otherwise the key is now a Key const &, which needs a copy when inserting.

So far, I don't need additional interface for users.

**Comment by kleunen** [comment]
> > Also, The STL allows insertion of a pair (pair<key, value>), which allowes moving in the complete <key, value> pair moving in the map. Should we add this ? Otherwise the key is now a Key const &, which needs a copy when inserting.
> 
> So far, I don't need additional interface for users.

I think it would be useful, you make a copy now for the key, but if this is a temporary, this is not needed.

**Comment by redboltz** [comment]
> > > Also, The STL allows insertion of a pair (pair<key, value>), which allowes moving in the complete <key, value> pair moving in the map. Should we add this ? Otherwise the key is now a Key const &, which needs a copy when inserting.
> > 
> > 
> > So far, I don't need additional interface for users.
> 
> I think it would be useful, you make a copy now for the key, but if this is a temporary, this is not needed.

I'm not sure what is this. Which one of https://en.cppreference.com/w/cpp/container/unordered_map/insert ?

**Comment by redboltz** [comment]
If you can separate additional interface and removing too much requirement, please implement removing requirement first.
I need it to integrate subscription_map to test_broker.

**Comment by kleunen** [comment]
> > > > Also, The STL allows insertion of a pair (pair<key, value>), which allowes moving in the complete <key, value> pair moving in the map. Should we add this ? Otherwise the key is now a Key const &, which needs a copy when inserting.
> > > 
> > > 
> > > So far, I don't need additional interface for users.
> > 
> > 
> > I think it would be useful, you make a copy now for the key, but if this is a temporary, this is not needed.
> 
> I'm not sure what is this. Which one of https://en.cppreference.com/w/cpp/container/unordered_map/insert ?

It is (2), unordered_map you can do: 
````C++
map.insert(std::make_pair("test", "1234"));
````

**Comment by redboltz** [comment]
> > > > > Also, The STL allows insertion of a pair (pair<key, value>), which allowes moving in the complete <key, value> pair moving in the map. Should we add this ? Otherwise the key is now a Key const &, which needs a copy when inserting.
> > > > 
> > > > 
> > > > So far, I don't need additional interface for users.
> > > 
> > > 
> > > I think it would be useful, you make a copy now for the key, but if this is a temporary, this is not needed.
> > 
> > 
> > I'm not sure what is this. Which one of https://en.cppreference.com/w/cpp/container/unordered_map/insert ?
> 
> It is (2), unordered_map you can do:
> 
> ```c++
> map.insert(std::make_pair("test", "1234"));
> ```
> 
> I can add this to interface, existing code won't break

Ok, it is no problem. Thanks.

**Comment by kleunen** [comment]
I will create PR

**Comment by kleunen** [comment]
PR #711

**Comment by kleunen** [comment]
See PR #713 for updated approach

**Pull request merged**
