### PR TITLE
Update the version to 12.1.0.

### PR DESCRIPTION
**Pull request by redboltz**

### CODE REVIEW

**Comment by redboltz** [comment]
Pending.
Restart after #927 and #928 are solved.

**Comment by Tradias** [comment]
@redboltz I am also working on another improvement regarding includes when MQTT_STD_XXX options are set.

**Comment by redboltz** [comment]
> @redboltz I am also working on another improvement regarding includes when MQTT_STD_XXX options are set.

Ok, I will wait.

**Comment by redboltz** [comment]
rebased.

**Pull request merged**
