### PR TITLE
Separate lifetime from content in wire protocol messages

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by redboltz** [comment]
I intentionally avoid embedding `mqtt::any` into message types and `mqtt::burrer`.

`mqtt::any` need to have non trivial destructor due to its type erasure mechanism. Even if move argument passing, the destructor is needed to be called.

Here is performance test:

```cpp
#include <any>
#include <memory>
#include <iostream>
#include <string>
#include <cstring>
#include <chrono>

std::shared_ptr<char[]> g;

inline void spa1(std::shared_ptr<char[]> a) {
    g = std::move(a);
}

inline void spa2(std::shared_ptr<char[]> a) {
    spa1(std::move(a));
}

inline void any1(std::any a) {
    auto s = std::any_cast<std::shared_ptr<char[]>>(a);
    g = std::move(s);
}

inline void any2(std::any a) {
    any1(std::move(a));
}

int main(int argc, char* argv[]) {
    if (argc != 2) {
        std::cout << "Usage: " << argv[0] << " times" << std::endl;
        return -1;
    }
    auto max = std::stoi(argv[1]);

    // prepare data
    auto spa = std::make_shared<char[]>(3);
    std::strcpy(spa.get(), "ABC");

    {
        std::cout << "spa" << std::endl;
        auto start = std::chrono::system_clock::now();
        for (int i = 0; i != max; ++i) {
            spa2(spa);
        }
        auto finish = std::chrono::system_clock::now();
        std::cout
            << std::chrono::duration_cast<std::chrono::milliseconds>(finish - start).count()
            << " ms"
            << std::endl;
    }
    {
        std::cout << "any" << std::endl;
        auto start = std::chrono::system_clock::now();
        for (int i = 0; i != max; ++i) {
            any2(spa);
        }
        auto finish = std::chrono::system_clock::now();
        std::cout
            << std::chrono::duration_cast<std::chrono::milliseconds>(finish - start).count()
            << " ms"
            << std::endl;
    }
}
```

I got the following result:

```
clang++ -std=c++17 comp_spa_any.cpp -O3                                                                                            ./a.out 100000000
spa
248 ms
any
1862 ms
```

So I want to keep `mqtt::shared_ptr_array` (`std::shared_ptr<char[]`> ) based implementation.

**Comment by jonesmz** [comment]
Then we should remove lifetime handling from the messages entirely, and keep the lifekeeper in the async_handler_t func.

Thoughts?

**Comment by redboltz** [comment]
> Then we should remove lifetime handling from the messages entirely, and keep the lifekeeper in the async_handler_t func.
> 
> Thoughts?

I think that we don't need to remove all of them. Because they don't have other better choices to replace. And if user uses `mqtt::buffer`, then they can avoid some of performance disadvantage. And I did it on my broker.

**Comment by jonesmz** [comment]
> I think that we don't need to remove all of them. Because they don't have other better choices to replace. And if user uses mqtt::buffer, then they can avoid some of performance disadvantage. And I did it on my broker.

I mean only for the message objects. The end-user API would stay the same.

**Comment by redboltz** [comment]
Message objects should be kept the current implementation.

**Comment by jonesmz** [comment]
I've updated the pull request to remove the lifetime tracking from the messages entirely.

The only thing that tracks lifetime inside the message objects now is the v5::properties.

The reason why I want to make this change is that I want to support a model where either an std::span, or a pair of iterators, can be passed in to any function that currently takes an std::vector.

The current model of requiring the lifetime tracking be bundled with the message object restricts the options that end users have for structuring their program.

**Comment by redboltz** [comment]
I'm not convinced yet. I need a time to consider it. Unfortunately, I don't have much time so far. But I continue to consider the issue.

**Comment by jonesmz** [comment]
Sure, I'm not in a rush.

**Comment by redboltz** [comment]
> The reason why I want to make this change is that I want to support a model where either an std::span, or a pair of iterators, can be passed in to any function that currently takes an std::vector.
> 
> The current model of requiring the lifetime tracking be bundled with the message object restricts the options that end users have for structuring their program.

I'm not 100% sure what you want to do yet. So I need to share the concept. I understand that `std::vector` is too concrete type. As you mentioned, `std::span`, a pair of iterators, or range v3 are more flexible types. I'm not sure range v3 standard proposal status but I think that it should be checked.

> any function that currently takes an std::vector

Could you clarify this? 

1. Are APIs that is called by user included? 

For example,

```cpp
    packet_id_t subscribe(
        std::vector<std::tuple<string_view, subscribe_options>> params,
        v5::properties props = {}
    );
```

2. Are handlers that are overridden by the user included?

For example,

```cpp
    virtual bool on_subscribe(packet_id_t packet_id,
                              std::vector<std::tuple<MQTT_NS::buffer, subscribe_options>> entries) = 0;
```

**Comment by jonesmz** [comment]
> I understand that std::vector is too concrete type. As you mentioned, std::span, a pair of iterators, or range v3 are more flexible types. 

Correct. message.hpp and v5_message.hpp do not care about the data type that user code is storing the "collection" of things as. Only that the data is provided. Currently these messages take an std::vector (of topics, or subscribe options, etc), but this can be made more generic.

> I'm not sure range v3 standard proposal status but I think that it should be checked.

Ranges is officially in C++20.

> Are handlers that are overridden by the user included?

No. No change to handlers.

> Are APIs that is called by user included?

Yes. This Pull Request is just preparation, but it also has the benefit of reducing the size of the basic_subscribe message, and the basic_publish message, because now these messages do not contain extra std::shared_ptr<char[]> objects.

**Comment by jonesmz** [comment]
An example of why I want to make this more generic.

(this example uses cpp17, for structured bindings, btw)

```cpp
            auto pTopics = std::make_unique<std::vector<std::tuple<MQTT_NS::buffer, MQTT_NS::subscribe_options>>>();
            pTopics->reserve(this->m_topicMap.size());
            for([[maybe_unused]] const auto & [topicPattern, handler] : this->m_topicMap)
            {
                pTopics->emplace_back(topicPattern, MQTT_NS::qos::exactly_once);
            }
            std::span<std::tuple<MQTT_NS::buffer, MQTT_NS::subscribe_options>> span = *pTopics;
            pMqttClient->async_subscribe(span, [pTopics = std::move(pTopics)](std::error_code ec)
            {
                BOOST_LOG(Debug) << "Finished subscribing to initial resource method topics"
                          << std::endl << "- ErrorCode: " << ec
                          << std::endl << "- Topics:    " << *pTopics;
            });
```

Right now, client:async_subscribe() will copy the std::vector<tuple<...>>. So I can't use the typical boost::asio pattern of preserving the lifetime of the variable that's going to be be used for the async operation in the CompletionToken.

This Pull Request does not fix this problem, but it makes fixing the problem easier in the future.

**Comment by redboltz** [comment]
Thank you adding comment.
I'm checking the performance difference between
1. Move operation of `mqtt::buffer` that has non null `shared_ptr_array` and empty `mqtt::any`

amd

2. Move operation of `as::buffer` that has non null `shared_ptr_array` and `mqtt::any` that has `mqtt::buffer`.

I guess that they have no big difference but I want to test it. So I need a time a little more.

**Comment by redboltz** [comment]
I've checked the performance difference and no significant difference is observed as I expected.  

Checking code:

```cpp
#include <iostream>
#include <chrono>
#include <string>

#include <mqtt_client_cpp.hpp>

int g;

void spa_empty_any1(mqtt::buffer, mqtt::any) {
    ++g;
}

void spa_empty_any2(mqtt::buffer buf, mqtt::any any) {
    spa_empty_any1(std::move(buf), std::move(any));
}

void spa_empty_any3(mqtt::buffer buf) {
    spa_empty_any2(std::move(buf), mqtt::any());
}

void asb_any1(boost::asio::const_buffer, mqtt::any) {
    ++g;
}

void asb_any2(boost::asio::const_buffer buf, mqtt::any any) {
    asb_any1(buf, std::move(any));
}

void asb_any3(mqtt::buffer buf) {
    auto ab = boost::asio::buffer(buf.data(), buf.size());
    asb_any2(ab, std::move(buf));
}


int main(int argc, char* argv[]) {
    if (argc != 2) {
        std::cout << "Usage: " << argv[0] << " times" << std::endl;
        return -1;
    }
    auto times = std::stoul(argv[1]);

    auto buf = mqtt::allocate_buffer("01234567890123456789012345678901234567890123456789");
    {
        std::cout << "mqtt::buffer with empty mqtt::any" << std::endl;
        auto start = std::chrono::system_clock::now();
        for (unsigned long i = 0; i != times; ++i) {
            spa_empty_any3(buf);
        }
        auto end = std::chrono::system_clock::now();
        std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms" << std::endl;
    }
    {
        std::cout << "as::buffer with mqtt::any that holds mqtt::buffer" << std::endl;
        auto start = std::chrono::system_clock::now();
        for (unsigned long i = 0; i != times; ++i) {
            asb_any3(buf);
        }
        auto end = std::chrono::system_clock::now();
        std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " ms" << std::endl;
    }
}
```

Result:

```
mqtt::buffer with empty mqtt::any
2212 ms
as::buffer with mqtt::any that holds mqtt::buffer
2215 ms
```

So I merge it. Thank you for waiting.

**Pull request merged**
